admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: "127.0.0.1"
      port_value: 9901
static_resources:
  listeners:
    - name: "bff-http-listener"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 8786
      traffic_direction: INBOUND
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                tracing:
                  provider:
                    name: envoy.tracers.zipkin
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
                      collector_cluster: tracing
                      collector_endpoint: "/api/v2/spans"
                      shared_span_context: false
                      collector_endpoint_version: HTTP_JSON
                stat_prefix: "ingress"
                codec_type: "AUTO"
                route_config:
                  name: "bff-http-route"
                  virtual_hosts:
                    - name: "bff-http-route"
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: "bff"
                http_filters:
                  - name: "envoy.router"
    - name: "books-svc-http-listener"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 8800
      traffic_direction: OUTBOUND
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                tracing:
                  provider:
                    name: envoy.tracers.zipkin
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
                      collector_cluster: tracing
                      collector_endpoint: "/api/v2/spans"
                      shared_span_context: true
                      collector_endpoint_version: HTTP_JSON
                stat_prefix: "egress"
                codec_type: "AUTO"
                route_config:
                  name: "books-svc-http-route"
                  virtual_hosts:
                    - name: "books-svc-http-route"
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: "books-svc"
                http_filters:
                  - name: "envoy.router"
    - name: "reviews-svc-http-listener"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 8801
      traffic_direction: OUTBOUND
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                tracing:
                  provider:
                    name: envoy.tracers.zipkin
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
                      collector_cluster: tracing
                      collector_endpoint: "/api/v2/spans"
                      shared_span_context: true
                      collector_endpoint_version: HTTP_JSON
                stat_prefix: "egress"
                codec_type: "AUTO"
                route_config:
                  name: "reviews-svc-http-route"
                  virtual_hosts:
                    - name: "reviews-svc-http-route"
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: "reviews-svc"
                http_filters:
                  - name: "envoy.router"
  clusters:
    - name: "bff"
      connect_timeout: "0.25s"
      type: "static"
      lb_policy: "RANDOM"
      hosts:
        - socket_address:
            address: "127.0.0.1"
            port_value: 8080
    - name: "books-svc"
      connect_timeout: "0.25s"
      type: "strict_dns"
      lb_policy: "ROUND_ROBIN"
      hosts:
        - socket_address:
            address: "envoy-snt-books-svc"
            port_value: 8786
    - name: "reviews-svc"
      connect_timeout: "0.25s"
      type: "strict_dns"
      lb_policy: "ROUND_ROBIN"
      hosts:
        - socket_address:
            address: "envoy-snt-reviews-svc"
            port_value: 8786
    - name: "tracing"
      connect_timeout: 1s
      type: "strict_dns"
      lb_policy: "RANDOM"
      hosts:
        - socket_address:
            address: "tracing"
            port_value: 9411
