admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: "127.0.0.1"
      port_value: 9901
static_resources:
  listeners:
    - name: "fe-http-listener"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 8786
      filter_chains:
        - filters:
            - name: "envoy.http_connection_manager"
              config:
                stat_prefix: "ingress"
                codec_type: "AUTO"
                route_config:
                  name: "fe-http-route"
                  virtual_hosts:
                    - name: "fe-http-route"
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: "fe"
                http_filters:
                  - name: "envoy.router"
  clusters:
    - name: "fe"
      connect_timeout: "0.25s"
      type: "static"
      lb_policy: "RANDOM"
      hosts:
        - socket_address:
            address: "127.0.0.1"
            port_value: 8080
